import Head from 'next/head'
import { useState } from 'react'
import Blogs from '../components/Blogs/Blogs'
import BlogCategories from '../components/Blogs/BlogCategories'

export default function Home({blogs}) {

	const [isCty, setIsCty] = useState('all')

	return (
    	<div className="px-5">
    		<Head>
          		<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
        	</Head>		

			<main className="py-10 container">
				<BlogCategories 
					isCty={isCty}
					setIsCty={setIsCty}
					categories={blogs.map(blog => blog.category)}/>
				<Blogs 
					blogs={blogs.filter(blog => blog.category.includes(isCty === 'all' ? '' : isCty.toLowerCase()))}/>
			</main>

      </div>
  	)
}


export const getStaticProps = async() => {
	const res = await fetch('http://localhost:4000/blogs')
	const blogs = await res.json()

	return {
		props: {
			blogs
		},
		revalidate: 60
	}
}
